universe = vanilla
executable = runAnalysis.sh
arguments = $(rootfile)
should_transfer_files = YES
output = output/condor.$(ClusterId).$(ProcId).out
error = error/condor.$(ClusterId).$(ProcId).err
log = log/condor.$(ClusterId)_$(Process).log
transfer_input_files = /etc/ciconnect/templates/cmssw_setup.sh, SkimTree.py, FileList.txt, Loader.h

transfer_output_remaps = "SkimmedTree.root = data/Filelist_bkg_run2/WJetsToLNu_HT-800To1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_MC25ns_LegacyMC_20170328/SkimmedTree_$(Process).root"
queue rootfile from Filelists/Filelist_bkg_run2/bkg_run2_2.txt