universe = vanilla
use_x509userproxy = true
executable = runAnalysis.sh
should_transfer_files = YES
output = output/condor.$(ClusterId).$(ProcId).out
error = error/condor.$(ClusterId).$(ProcId).err
log = log/condor.$(ClusterId).$(Process).log
transfer_input_files = /etc/ciconnect/templates/cmssw_setup.sh, SkimTree.py, MonoHBranchReader.py, Loader.h

arguments = $(rootfile) Filelist_bkg_run4v2/GJets_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_MC25ns_LegacyMC_20170328 $(Process)
transfer_output_remaps = "Output_SkimmedTree.root = data/Filelist_bkg_run4v2/GJets_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_MC25ns_LegacyMC_20170328/BROuptut_$(Process).root"
queue rootfile from Filelists/Filelist_bkg_run4v2/bkg_run4v2_1.txt
