universe = vanilla
use_x509userproxy = true
executable = runAnalysis.sh
should_transfer_files = YES
output = output/condor.$(ClusterId).$(ProcId).out
error = error/condor.$(ClusterId).$(ProcId).err
log = log/condor.$(ClusterId)_$(Process).log
transfer_input_files = /etc/ciconnect/templates/cmssw_setup.sh, SkimTree.py, MonoHBranchReader.py, MonoHbbQuantities.py, BTagCalibrationStandalone.cpp, BTagCalibrationStandalone.h, CSVv2_ichep.csv, PileUpWeights.h, PileUpWeights.py, Loader.h

